### ISSUE TITLE
No entities

### ISSUE THREAD

**Issue by rfam13** [joncar/ha-fpa#4]
Hello, after installing and setting up this integration.  I have successfully logged in but no sensor has been added to HA.  This is all that shows under devices and integrations now.

![Screenshot_20220607-232058_Home Assistant.jpg](https://user-images.githubusercontent.com/98683384/172524728-709cb6d3-93bc-4544-97ed-529a43586e94.jpg)

Any help would be appreciated, got a new born and a babybrezza would love to get this in HA!

**Comment by dmellenthin** [comment]
That symptom sounds similar to Issue #1 , and that mentions how to enable additional logging.

I hope you get this working, from one very happy user to another :)

**Comment by rfam13** [comment]
Thanks for the tip, that was easy enough.  I had a bottle that was water only so I hadn't set the formula setting, got rid of it and everything is working great now.  Thank you!

Error while setting up fpa platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fpa/sensor.py", line 39, in async_setup_entry
    await api.connect_to_device(device.device_id)
  File "/usr/local/lib/python3.9/site-packages/pybabyfpa/__init__.py", line 351, in connect_to_device
    await self.get_device_details(device_id)
  File "/usr/local/lib/python3.9/site-packages/pybabyfpa/__init__.py", line 331, in get_device_details
    device.update_details(j)
  File "/usr/local/lib/python3.9/site-packages/pybabyfpa/__init__.py", line 157, in update_details
    self.bottles = [FpaBottle(b) for b in json["bottles"]]
  File "/usr/local/lib/python3.9/site-packages/pybabyfpa/__init__.py", line 157, in <listcomp>
    self.bottles = [FpaBottle(b) for b in json["bottles"]]
  File "/usr/local/lib/python3.9/site-packages/pybabyfpa/__init__.py", line 59, in __init__
    self.formula = FpaFormula(json["formula"])
KeyError: 'formula'
